# -*- coding: utf-8 -*-
"""ClassificationTree01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fn0h6H45Zqa0E01UJkPPdAr1m8PV2u61
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import train_test_split
from sklearn import metrics

data = {
    'Age': [25, 35, 45, 20, 30, 50, 60, 40, 55, 28],
    'Income': [50000, 70000, 90000, 35000, 60000, 110000, 130000, 85000, 120000, 55000],
    'Bought': [0, 0, 1, 0, 0, 1, 1, 1, 1, 0] # 0 for No, 1 for Yes
}
df = pd.DataFrame(data)
df

X = df[['Age', 'Income']]
y = df['Bought']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

clf = DecisionTreeClassifier(random_state=1)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
plot_tree(clf, feature_names=['Age', 'Income'], class_names=['No Buy', 'Buy'], filled=True)
plt.show()